import type { Metadata } from "next";
import { auth0 } from "@/lib/auth0";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from '@/app/components/nav-bar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth0.getSession();
  const user = session?.user || null;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {user && <NavBar />}
        <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
          {children}

          <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center"></footer>
        </div>
      </body>
    </html>
  );
}
